name: Build Android APK
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Prepare Spec
        run: |
          if [ -f "spec.txt" ]; then
            mv spec.txt buildozer.spec
          fi

      - name: Build with Buildozer
        uses: ArtemSerebrenninkov/buildozer-action@v1
        with:
          buildozer_version: master
          command: android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Sody-App-Final
          path: bin/*.apk
          
