name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Spec
        run: |
          cp spec.txt buildozer.spec || echo "already exists"

      - name: Build with Buildozer
        uses: ArtemSerebrenninkov/buildozer-action@v1
        with:
          buildozer_version: master
          command: android debug
          
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Sody-App-Final
          path: bin/*.apk
          
